on:
  workflow_dispatch:
    # schedule:
    #    - cron: "0 0 * * *" # every day
name: Update google scholar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      # setup python
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # cache pip
      - name: Cache pip
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      # pip install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly pytz pandas plotly
      - name: Update google scholar
        id: update
        run: |
          python scripts/scholar.py
          # if there is not change (use git), exit 0
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          message: "Update google scholar ${{ env.NOW }}"
          author_email: 'github-actions[bot]@users.noreply.github.com'
          author_name: 'github-actions[bot]'
  publish:
    uses: ./.github/workflows/jekyll.yml
    needs: build
    secrets: inherit
